### ISSUE TITLE
panic when the operand is user defined type

### ISSUE THREAD

**Issue by moutend** [ToQoz/gopwt#33]
I found a bug that `assert.OK` panics when the operand is user defined type. Here's the code to reproduce that panic:

```go
package main

import (
	"flag"
	"os"

	"github.com/ToQoz/gopwt"
	"github.com/ToQoz/gopwt/assert"

	"testing"
)

type myint int

const two myint = 2

func TestMain(m *testing.M) {
	flag.Parse()
	gopwt.Empower()
	os.Exit(m.Run())
}

func TestFoo(t *testing.T) {
	a := myint(6)
	assert.OK(t, a == 3*two)
}
```

The output was:

```console
% go test
--- FAIL: TestFoo (0.00s)
panic: interface conversion: interface {} is main.myint, not int [recovered]
	panic: interface conversion: interface {} is main.myint, not int

goroutine 5 [running]:
testing.tRunner.func1(0xc4200d40f0)
	/usr/local/Cellar/go/1.9.4/libexec/src/testing/testing.go:711 +0x2d2
panic(0x112f700, 0xc420054780)
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/panic.go:491 +0x283
github.com/ToQoz/gopwt/translatedassert.OpMUL(0x1122f80, 0x1172388, 0x1122f40, 0x1172390, 0x11e6128, 0xf)
	/Users/mba/go/src/github.com/ToQoz/gopwt/translatedassert/op.go:99 +0x86a
github.com/moutend/bar.TestFoo(0xc4200d40f0)
	/var/folders/zg/fbcdm57j5vnc9m_90fjbr1fc0000gn/T/365782421/src/github.com/moutend/bar/main_test.go:23 +0x66
testing.tRunner(0xc4200d40f0, 0x1161d90)
	/usr/local/Cellar/go/1.9.4/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.4/libexec/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/moutend/bar	0.014s
exit status 1
exit status 1
FAIL	github.com/moutend/bar	0.831s
```

This is not a fatal bug because there is workaround like:

```go
package main

import (
	"flag"
	"os"

	"github.com/ToQoz/gopwt"
	"github.com/ToQoz/gopwt/assert"

	"testing"
)

type myint int

const two myint = 2

func TestMain(m *testing.M) {
	flag.Parse()
	gopwt.Empower()
	os.Exit(m.Run())
}

func TestFoo(t *testing.T) {
	a := myint(6)
	b := 3 * two
	assert.OK(t, a == b)
}
```

The code above works.
```console
% go test
PASS
ok  	github.com/moutend/foo	0.013s
```

Again, this is not a fatal bug, but it'll be helpful if fixed. Thanks.

**Comment by ToQoz** [comment]
Thank you for report !

I confirmed it. It should be solved, but  I don't have good idea yet. Please give me some time.
